name: pokerspot_user_app
description: 'A new Flutter project.'

publish_to: 'none'
version: 1.1.2+35

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  go_router: ^14.0.2
  cached_network_image: ^3.3.1
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.4
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  retrofit: ^4.0.3
  dio: ^5.4.0
  collection: ^1.18.0
  fluttertoast: ^8.2.4
  logger: ^2.0.2+1
  intl:
  loader_overlay: ^4.0.0
  json_annotation: ^4.8.1
  pull_to_refresh: ^2.0.0

  flutter_localizations:
    sdk: flutter
  geolocator: ^12.0.0
  change_app_package_name: ^1.1.0
  firebase_core: ^3.1.0
  card_swiper: ^3.0.1
  url_launcher: ^6.2.5
  permission_handler: ^11.3.1
  flutter_inappwebview: ^5.8.0
  photo_view: ^0.15.0
  timeago: ^3.6.1

  # 구글
  firebase_analytics: ^11.0.1
  firebase_crashlytics: ^4.0.1
  google_maps_flutter: ^2.2.8

  # 카카오
  kakao_flutter_sdk_user: ^1.9.1+2 # 카카오 로그인 API 패키지
  kakao_flutter_sdk_share: ^1.9.1+2 # 카카오톡 공유 API 패키지
  kakao_flutter_sdk_navi: ^1.9.1+2 # 카카오내비 API 패키지
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.2.3
  drift_dev: ^2.18.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  freezed: ^2.3.2
  flutter_launcher_icons: '^0.13.1'

flutter:
  assets:
    - assets/

  uses-material-design: true

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon.png'
  min_sdk_android: 26
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
