default_platform(:android)

platform :android do

  lane :internal do
    previous_build_number = google_play_track_version_codes(
      package_name:"com.pokerspot.user",
      track: "internal",
      json_key: "/projects/pokerspot_user_app/android/fastlane/play-store-credentials.json",
    )[0]

    current_build_number = previous_build_number + 1
    
    
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
      track: 'internal',
      release_status: 'draft',
      aab: '/projects/pokerspot_user_app/build/app/outputs/bundle/release/app-release.aab',
      version_code: current_build_number,
    )
  end
end
