platform :android do
    desc "PokerSpot Android Application"
    lane :distribute do
        build_android_app(
            gradle(
                task: 'assemble',
                build_type: 'Release'
            )
        )
        # build_android_app is a built-in fastlane action.
        # firebase_app_distribution(
        #     app: "1:159510515978:android:84608530601bb135ec6af3",
        #     testers: "wkdgus116490@gmail.com, wkdgus1164@gmail.com",
        #     release_notes: "테스트 출시!",
        #     apk_path: "../build/app/outputs/apk/release/app-release.apk"
        # )
        
    end
end